a = input()
b=len(a)
A=a.count("A")
T=a.count("T")
G=a.count("G")
C=a.count("C")
GC=100*(C+G)/(A+C+G+T)
print("Sequence: " +a)
print("Lenght: " +b)
print("A: " +A)
print("T: " +T)
print("G: " +G)
print("C: " +C)
print("CG " +CG)

